name = "iotomr-standard"
author = "bennetrr"
version = "{{PACK_VERSION}}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d0727fa8ee3f76206ccd620e946d0d73274b3534c4464e100f11f7509739763"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
