name: Build modpack
description: Builds a modpack for modrinth

inputs:
  edition:
    description: Edition name
    required: true
  version:
    description: Modpack version
    required: true
runs:
  using: composite
  steps:
    - name: Download packwiz
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ github.token }}
        repo: packwiz/packwiz
        workflow: go.yml
        name: Linux 64-bit x86

    - name: Install packwiz
      run: |
        sudo mv packwiz /usr/bin/packwiz
        sudo chmod +x /usr/bin/packwiz
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install jq and yq
      run: |
        sudo apt install -y jq
        pip install yq
      shell: bash

    - name: Set version fields
      run: |
        tomlq -t '.version = "${{ inputs.version }}"' pack.toml > pack.toml.tmp
        mv pack.toml.tmp pack.toml
        
        jq '.overrides.minecraft["+recommends"].iotomr = ">${{ inputs.version }}"' config/fabric_loader_dependencies.json > fld.json.tmp
        mv fld.json.tmp config/fabric_loader_dependencies.json

        jq '.main_menu.bottom_right[0].text |= sub("{{PACK_VERSION}}"; "${{ inputs.version }}")' config/isxander-main-menu-credits.json > mmc.json.tmp
        mv mmc.json.tmp config/isxander-main-menu-credits.json
      shell: bash
      working-directory: ${{ inputs.edition }}

    - name: Build modrinth modpack
      run: |
        packwiz modrinth export
      shell: bash
      working-directory: ${{ inputs.edition }}

    - name: Upload modpack as artifact
      uses: actions/upload-artifact@v4
      with:
        name: iotomr-${{ inputs.edition }}-${{ inputs.version }}.mrpack
        path: ${{ inputs.edition }}/iotomr-${{ inputs.edition }}-${{ inputs.version }}.mrpack
