name = "iotomr-plus"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377c69124244f54992a31b6a7f3eb9bfb8ca881dbd2cbd2d28e3d8318a643154"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
