name = "iotomr-plus"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "848f343bc43746deb132b694ad92dcc80bfaf47cd585d3f9e7c20206b394faee"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = []
