name = "iotomr"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e1356b9ec5bcabff23749e41a35646df3abeb5637076f63d6bceacc1dd775d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
