name = "iotomr"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63f9b160953417b5a7f280df7299010504bd1f22256dd09033ecb8f9081cfc1b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
