name = "iotomr"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90df58bf6d3d04ab4cc6b31b897b6763c63a98e9970caeaf8642d901f4ea228d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
