name = "iotomr"
author = "bennetrr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44bffb74bf4ce113db12d4b4e8d95270d7025aea2e757ed3302a7cbd76edab2d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
