name: Build and release

on:
  push:
    branches:
      - release

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get-release-version.outputs.version }}
      version-name: ${{ steps.get-release-version.outputs.version-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version
        id: get-release-version
        uses: wemogy/get-release-version-action@v4.3.2
        with:
          prefix: v
          create-tag: "true"
          git-username: bennetrr
          git-email: 76742318+bennetrr@users.noreply.github.com
          mode: semantic

  build-modpack:
    name: Build modpack
    needs: 
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Download packwiz
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ github.token }}
          repo: packwiz/packwiz
          workflow: go.yml
          name: Linux 64-bit x86

      - name: Install packwiz
        run: |
          sudo mv packwiz /usr/bin/packwiz
          sudo chmod +x /usr/bin/packwiz

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install jq and yq
        run: |
          sudo apt install -y jq
          pip install yq

      - name: Set version fields
        run: |
          tomlq -t '.version = "${{ needs.setup.outputs.version }}"' pack.toml > pack.toml.tmp
          mv pack.toml.tmp pack.toml
          
          jq '.overrides.minecraft["+recommends"].iotomr = ">${{ needs.setup.outputs.version }}"' config/fabric_loader_dependencies.json > fld.json.tmp
          mv fld.json.tmp config/fabric_loader_dependencies.json

          jq '.main_menu.bottom_right[0].text |= sub("{{PACK_VERSION}}"; "${{ needs.setup.outputs.version }}")' config/isxander-main-menu-credits.json > mmc.json.tmp
          mv mmc.json.tmp config/isxander-main-menu-credits.json
        working-directory: modpack

      - name: Build modrinth modpack
        run: |
          packwiz modrinth export
        working-directory: modpack

      - name: Upload modpack as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iotomr-${{ needs.setup.outputs.version }}.mrpack
          path: modpack/iotomr-${{ needs.setup.outputs.version }}.mrpack

  build-crafting-tweak-logs-to:
    name: 'Build Crafting Tweak: Logs to...'
    needs: 
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build datapack
        run: |
          zip -r crafting-tweak-logs-to-${{ needs.setup.outputs.version }}.zip *
        working-directory: crafting-tweak-logs-to/pack

      - name: Upload modpack as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crafting-tweak-logs-to-${{ needs.setup.outputs.version }}.zip
          path: crafting-tweak-logs-to/pack/crafting-tweak-logs-to-${{ needs.setup.outputs.version }}.zip

  github-release:
    name: Create GitHub release
    needs:
      - setup
      - build-modpack
      - build-crafting-tweak-logs-to
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Version ${{ needs.setup.outputs.version }}
          tag: ${{ needs.setup.outputs.version-name }}
          generateReleaseNotes: true
          commit: ${{ github.head_ref || github.ref_name }}
          artifacts: artifacts/*
